---
title: "Tester"
author: "Kristina Fauss"
date: "3/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(shinythemes)
library(tidyverse)
library(palmerpenguins)
library(here)
library(sf)
```


```{r}
# Read in Burn Scar & LFM data here as shapefile:
eco261ab_cent_rec <- read_sf(dsn = here("BurnScarsFRAP_wRecLFM_Chamise_CentEco261AB_Refined022021"))

```

```{r}
# Ensure numeric
eco261ab_cent_rec$LFM_Av20km <- as.numeric(eco261ab_cent_rec$LFM_Av20km)
eco261ab_cent_rec$area_km2 <- as.numeric(eco261ab_cent_rec$area_km2)
# Drop NA's
eco261ab_cent_rec <- eco261ab_cent_rec %>%
  drop_na(area_km2) %>%
  drop_na(LFM_Av20km)
```

```{r}
# Plot all data
ggplot(data=eco261ab_cent_rec, 
       mapping=aes(x=LFM_Av20km,
                   y=area_km2))+
  geom_point()
```

```{r}
# Min and max vals

min_lfm <- min(eco261ab_cent_rec$LFM_Av20km)
min_lfm

max_lfm <- max(eco261ab_cent_rec$LFM_Av20km)
max_lfm
```


```{r}
# Cut & mean & plot 1/3

#Seq <- c(55,75,95,115,135,155,175,195) # c function returns a 1 d vector array
lfm_step <- 20
Seq <- seq(min_lfm, max_lfm+lfm_step,lfm_step)
Seq
```

```{r}
# Cut & mean & plot 2/3

lfm.class <- cut(eco261ab_cent_rec$LFM_Av20km, Seq, include.lowest = TRUE)
mean.area <- tapply(eco261ab_cent_rec$area_km2, lfm.class, mean)
class.mids <- Seq[-1] - diff(Seq)/2

#lfm.class
length(class.mids)
class.mids
length(mean.area)
mean.area
```

```{r}
# Cut & mean & plot 3/3
plot(mean.area~class.mids,
     xlab='LFM',
     ylab='Average Fire Size',
     xlim=range(Seq))
```


